"""
BRONZE LAYER
─────────────────────────────────────────────────────────────────────────────
Ingests raw Spotify JSON files exactly as received, without any transformation.
Stores them under:   bucket/reproduccion/bronze/
Metadata (schema, record counts) is written to: bucket/reproduccion/bronze/_meta/

MinIO is simulated via a local directory tree (same bucket layout).
In production replace LOCAL_ROOT with an actual MinIO/S3 path and swap
open() calls for minio.put_object() / boto3.upload_fileobj().
─────────────────────────────────────────────────────────────────────────────
"""

import json
import os
import shutil
import hashlib
from datetime import datetime, timezone
from pathlib import Path

# ── Config ────────────────────────────────────────────────────────────────────
BASE_DIR   = Path(__file__).resolve().parent.parent
DATA_DIR   = BASE_DIR / "data"
LOCAL_ROOT = BASE_DIR / "bucket"               # simulates MinIO root
BRONZE_PATH = LOCAL_ROOT / "reproduccion" / "bronze"
META_PATH   = BRONZE_PATH / "_meta"


# ── Helpers ───────────────────────────────────────────────────────────────────

def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def infer_schema(records: list[dict]) -> dict[str, set]:
    """Return {field: set_of_python_types} across all records."""
    schema: dict[str, set] = {}
    for r in records:
        for k, v in r.items():
            schema.setdefault(k, set())
            schema[k].add(type(v).__name__)
    return {k: list(v) for k, v in schema.items()}


def load_raw_json(path: Path) -> list[dict]:
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    if isinstance(data, dict):          # some exports wrap in a dict
        data = list(data.values())[0]
    if not isinstance(data, list):
        raise ValueError(f"Unexpected JSON structure in {path.name}")
    return data


# ── Main ingestion ─────────────────────────────────────────────────────────────

def ingest(source_dir: Path = DATA_DIR) -> dict:
    """
    Scan source_dir for Spotify JSON files, copy them raw into the bronze
    bucket layer, and write per-file + aggregated metadata.

    Returns a summary dict consumed by the pipeline orchestrator.
    """
    BRONZE_PATH.mkdir(parents=True, exist_ok=True)
    META_PATH.mkdir(parents=True, exist_ok=True)

    import re as _re
    all_found = sorted(source_dir.glob("Streaming_History_Audio_*.json"))
    if not all_found:
        raise FileNotFoundError(
            f"No Streaming_History_Audio_*.json files found in {source_dir}"
        )

    # Real Spotify exports have a numeric suffix: e.g. _0.json, _1.json
    # Sample files generated by generate_sample_data.py do NOT have that suffix.
    # When both coexist, keep only real files to avoid cross-file duplicates.
    real_files   = [f for f in all_found if _re.search(r"_\d+\.json$", f.name)]
    sample_files = [f for f in all_found if not _re.search(r"_\d+\.json$", f.name)]

    if real_files and sample_files:
        print(f"  ⚠  Ignoring {len(sample_files)} sample file(s) — real Spotify files detected.")
        print(f"     Skipped: {[f.name for f in sample_files]}")
        json_files = real_files
    else:
        json_files = all_found

    ingested_files = []
    total_records  = 0
    all_records    = []

    print(f"\n{'─'*60}")
    print("  BRONZE – Raw ingestion")
    print(f"{'─'*60}")

    for src in json_files:
        records = load_raw_json(src)
        total_records += len(records)
        all_records.extend(records)

        # ── Copy raw file ──────────────────────────────────────────────────
        dest = BRONZE_PATH / src.name
        shutil.copy2(src, dest)

        # ── Per-file metadata ──────────────────────────────────────────────
        file_meta = {
            "file_name":       src.name,
            "source_path":     str(src),
            "bronze_path":     str(dest),
            "sha256":          sha256_file(src),
            "record_count":    len(records),
            "ingested_at":     datetime.now(timezone.utc).isoformat(),
            "size_bytes":      src.stat().st_size,
        }
        meta_file = META_PATH / f"{src.stem}_meta.json"
        with open(meta_file, "w", encoding="utf-8") as f:
            json.dump(file_meta, f, indent=2)

        ingested_files.append(file_meta)
        print(f"  ✓  {src.name:55s}  {len(records):>5} records")

    # ── Aggregated schema metadata ─────────────────────────────────────────
    schema = infer_schema(all_records)
    agg_meta = {
        "layer":            "bronze",
        "bucket_path":      "bucket/reproduccion/bronze",
        "total_files":      len(ingested_files),
        "total_records":    total_records,
        "schema":           schema,
        "fields":           list(schema.keys()),
        "ingested_at":      datetime.now(timezone.utc).isoformat(),
        "files":            ingested_files,
    }
    with open(META_PATH / "aggregated_meta.json", "w", encoding="utf-8") as f:
        json.dump(agg_meta, f, indent=2)

    print(f"\n  Total records ingested : {total_records:,}")
    print(f"  Schema fields detected : {len(schema)}")
    print(f"  Bronze path            : {BRONZE_PATH}")
    print(f"{'─'*60}\n")

    return agg_meta


if __name__ == "__main__":
    ingest()
